# common values at global level. 
namespace: hello

# micro-service specific values inside each service subsection.
hello:
  image: 
    name: 100682590469.dkr.ecr.eu-west-2.amazonaws.com/dev-container-platform
    tag: main-0c2db21
    pullpolicy: IfNotPresent
  container:
    port: 8080
    protocol: TCP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  replicas: 3
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: helloworld
    hosts:
      - helloworld-demo.test
